# Generated by Django 4.2.24 on 2025-09-23 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_customerloyaltyprogram_layawayplan_layawayreminder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total Deliveries')),
                ('on_time_deliveries', models.PositiveIntegerField(default=0, verbose_name='On-Time Deliveries')),
                ('late_deliveries', models.PositiveIntegerField(default=0, verbose_name='Late Deliveries')),
                ('total_items_received', models.PositiveIntegerField(default=0, verbose_name='Total Items Received')),
                ('defective_items', models.PositiveIntegerField(default=0, verbose_name='Defective Items')),
                ('returned_items', models.PositiveIntegerField(default=0, verbose_name='Returned Items')),
                ('total_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Order Value (Toman)')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Average Order Value (Toman)')),
                ('average_response_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Average Response Time (Hours)')),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Overall Rating (0-5)')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Last Calculated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='customers.supplier', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Supplier Performance Metrics',
                'verbose_name_plural': 'Supplier Performance Metrics',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='Payment Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Payment Amount (Toman)')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('credit_card', 'Credit Card'), ('promissory_note', 'Promissory Note')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference, cheque number, etc.', max_length=100, verbose_name='Reference Number')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.purchaseorder', verbose_name='Purchase Order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.supplier', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'verbose_name_plural': 'Supplier Payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['payment_number'], name='customers_s_payment_1d1f7e_idx'), models.Index(fields=['supplier'], name='customers_s_supplie_7a8c9e_idx'), models.Index(fields=['purchase_order'], name='customers_s_purchas_b05ea9_idx'), models.Index(fields=['payment_date'], name='customers_s_payment_562413_idx'), models.Index(fields=['status'], name='customers_s_status_5e396e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('delivery_number', models.CharField(max_length=50, unique=True, verbose_name='Delivery Number')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Delivery Date')),
                ('scheduled_time_start', models.TimeField(blank=True, null=True, verbose_name='Scheduled Start Time')),
                ('scheduled_time_end', models.TimeField(blank=True, null=True, verbose_name='Scheduled End Time')),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery Date')),
                ('delivery_method', models.CharField(choices=[('pickup', 'Pickup'), ('courier', 'Courier'), ('postal', 'Postal Service'), ('freight', 'Freight'), ('supplier_delivery', 'Supplier Delivery')], max_length=20, verbose_name='Delivery Method')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking Number')),
                ('carrier_name', models.CharField(blank=True, max_length=100, verbose_name='Carrier Name')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Delivery Status')),
                ('delivery_address', models.TextField(verbose_name='Delivery Address')),
                ('delivery_contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('delivery_contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Contact Phone')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Cost (Toman)')),
                ('is_delivery_paid', models.BooleanField(default=False, verbose_name='Is Delivery Cost Paid')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Special Instructions')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('received_by_name', models.CharField(blank=True, max_length=100, verbose_name='Received By (Name)')),
                ('received_by_signature', models.TextField(blank=True, verbose_name='Received By (Signature)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to='customers.purchaseorder', verbose_name='Purchase Order')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Delivery Schedule',
                'verbose_name_plural': 'Delivery Schedules',
                'ordering': ['scheduled_date', 'scheduled_time_start'],
                'indexes': [models.Index(fields=['delivery_number'], name='customers_d_deliver_64c665_idx'), models.Index(fields=['purchase_order'], name='customers_d_purchas_d520bd_idx'), models.Index(fields=['scheduled_date'], name='customers_d_schedul_590785_idx'), models.Index(fields=['status'], name='customers_d_status_642892_idx'), models.Index(fields=['tracking_number'], name='customers_d_trackin_93cc92_idx')],
            },
        ),
    ]
