# Generated by Django 4.2.7 on 2025-09-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_superadmin_models'),
    ]

    operations = [
    ]
