# Generated by Django 4.2.7 on 2025-09-18 23:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_auto_20250919_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('superadmin', 'Super Admin'), ('user', 'Regular User')], max_length=20, verbose_name='User Type')),
                ('user_id', models.PositiveIntegerField(verbose_name='User ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('tenant_schema', models.CharField(max_length=100, verbose_name='Tenant Schema')),
                ('tenant_name', models.CharField(blank=True, max_length=200, verbose_name='Tenant Name')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('view', 'View Record'), ('export', 'Export Data'), ('import', 'Import Data'), ('tenant_switch', 'Switch Tenant'), ('impersonation_start', 'Start Impersonation'), ('impersonation_end', 'End Impersonation')], max_length=50, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model Name')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='Object ID')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Action Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Request Path')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Request Method')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Tenant Access Log',
                'verbose_name_plural': 'Tenant Access Logs',
                'db_table': 'tenants_access_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='superadminsession',
            options={'ordering': ['-access_time'], 'verbose_name': 'Super Admin Session', 'verbose_name_plural': 'Super Admin Sessions'},
        ),
        migrations.RemoveIndex(
            model_name='superadminsession',
            name='tenants_sup_is_acti_4cdb1c_idx',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='theme_preference',
        ),
        migrations.RemoveField(
            model_name='superadminsession',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='superadminsession',
            name='started_at',
        ),
        migrations.AddField(
            model_name='superadmin',
            name='can_access_all_data',
            field=models.BooleanField(default=True, verbose_name='Can Access All Tenant Data'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='can_create_tenants',
            field=models.BooleanField(default=True, verbose_name='Can Create Tenants'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='can_suspend_tenants',
            field=models.BooleanField(default=True, verbose_name='Can Suspend Tenants'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='last_tenant_access',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superadminsession',
            name='access_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Access Time'),
        ),
        migrations.AlterField(
            model_name='superadminsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='superadminsession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active Session'),
        ),
        migrations.AlterField(
            model_name='superadminsession',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='Session Key'),
        ),
        migrations.AlterField(
            model_name='superadminsession',
            name='super_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tenants.superadmin', verbose_name='Super Admin'),
        ),
        migrations.AddIndex(
            model_name='superadminsession',
            index=models.Index(fields=['access_time'], name='tenants_sup_access__c786cc_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantaccesslog',
            index=models.Index(fields=['user_type', 'user_id'], name='tenants_acc_user_ty_85334c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantaccesslog',
            index=models.Index(fields=['tenant_schema'], name='tenants_acc_tenant__351b58_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantaccesslog',
            index=models.Index(fields=['action'], name='tenants_acc_action_3be01c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantaccesslog',
            index=models.Index(fields=['timestamp'], name='tenants_acc_timesta_281aad_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantaccesslog',
            index=models.Index(fields=['success'], name='tenants_acc_success_6b5fea_idx'),
        ),
    ]
