# Generated by Django 4.2.24 on 2025-09-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_subscriptionplan_billingcycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA Enabled'),
        ),
    ]
