# Generated by Django 4.2.24 on 2025-09-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_superadmin_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme')], default='light', max_length=10, verbose_name='Theme Preference'),
        ),
    ]
