# Generated by Django 4.2.24 on 2025-09-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_superadmin_theme_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('bulk_create', 'Bulk Create'), ('bulk_update', 'Bulk Update'), ('bulk_delete', 'Bulk Delete'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('tenant_create', 'Tenant Create'), ('tenant_update', 'Tenant Update'), ('tenant_suspend', 'Tenant Suspend'), ('tenant_activate', 'Tenant Activate'), ('user_impersonate', 'User Impersonate'), ('impersonation_end', 'Impersonation End'), ('backup_create', 'Backup Create'), ('backup_restore', 'Backup Restore'), ('system_maintenance', 'System Maintenance'), ('configuration_change', 'Configuration Change')], max_length=50, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model Name')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Object Representation')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON representation of field changes', verbose_name='Changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Request Path')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Request Method')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Additional Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Public Audit Log',
                'verbose_name_plural': 'Public Audit Logs',
                'db_table': 'tenants_publicauditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('login_blocked', 'Login Blocked (Rate Limited)'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('2fa_success', '2FA Verification Success'), ('2fa_failed', '2FA Verification Failed'), ('2fa_backup_used', '2FA Backup Token Used'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('suspicious_activity', 'Suspicious Activity Detected'), ('brute_force_attempt', 'Brute Force Attack Attempt'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('privilege_escalation', 'Privilege Escalation Attempt'), ('data_export', 'Data Export'), ('bulk_operation', 'Bulk Operation'), ('admin_impersonation', 'Admin Impersonation'), ('api_rate_limit', 'API Rate Limit Exceeded'), ('csrf_failure', 'CSRF Token Failure'), ('session_hijack', 'Potential Session Hijacking')], max_length=50, verbose_name='Event Type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severity Level')),
                ('username_attempted', models.CharField(blank=True, help_text='Username used in failed login attempts', max_length=150, verbose_name='Username Attempted')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Request Path')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Request Method')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the security event', verbose_name='Event Details')),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this security event has been investigated and resolved', verbose_name='Is Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Security Event',
                'verbose_name_plural': 'Public Security Events',
                'db_table': 'tenants_publicsecurityevent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicSuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('multiple_failed_logins', 'Multiple Failed Logins'), ('unusual_access_pattern', 'Unusual Access Pattern'), ('privilege_escalation', 'Privilege Escalation Attempt'), ('data_scraping', 'Data Scraping'), ('session_anomaly', 'Session Anomaly'), ('geographic_anomaly', 'Geographic Anomaly'), ('time_anomaly', 'Time-based Anomaly'), ('bulk_data_access', 'Bulk Data Access'), ('unauthorized_api_usage', 'Unauthorized API Usage'), ('suspicious_user_agent', 'Suspicious User Agent')], max_length=50, verbose_name='Activity Type')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', max_length=20, verbose_name='Risk Level')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('pattern_data', models.JSONField(default=dict, help_text='Data used for pattern detection and analysis', verbose_name='Pattern Data')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score (0.0 to 1.0) for this suspicious activity detection', verbose_name='Confidence Score')),
                ('is_investigated', models.BooleanField(default=False, verbose_name='Is Investigated')),
                ('investigated_at', models.DateTimeField(blank=True, null=True, verbose_name='Investigated At')),
                ('investigation_notes', models.TextField(blank=True, verbose_name='Investigation Notes')),
                ('is_false_positive', models.BooleanField(default=False, verbose_name='Is False Positive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Suspicious Activity',
                'verbose_name_plural': 'Public Suspicious Activities',
                'db_table': 'tenants_publicsuspiciousactivity',
                'ordering': ['-created_at'],
            },
        ),
    ]
