# Generated by Django 4.2.24 on 2025-09-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_publicauditlog_publicsecurityevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRateLimitAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='IP address, user ID, or other identifier', max_length=200, verbose_name='Identifier')),
                ('limit_type', models.CharField(choices=[('login', 'Login Attempts'), ('api_call', 'API Call'), ('password_reset', 'Password Reset'), ('2fa_verify', '2FA Verification'), ('data_export', 'Data Export'), ('bulk_operation', 'Bulk Operation'), ('search', 'Search Query'), ('report_generation', 'Report Generation')], max_length=50, verbose_name='Limit Type')),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint or view name', max_length=200, verbose_name='Endpoint')),
                ('attempts', models.PositiveIntegerField(default=1, verbose_name='Attempts')),
                ('window_start', models.DateTimeField(auto_now_add=True, verbose_name='Window Start')),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='Last Attempt')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is Blocked')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Blocked Until')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Public Rate Limit Attempt',
                'verbose_name_plural': 'Public Rate Limit Attempts',
                'db_table': 'tenants_publicratelimitattempt',
                'unique_together': {('identifier', 'limit_type', 'endpoint')},
            },
        ),
    ]
