# Generated by Django 4.2.24 on 2025-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_publicratelimitattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicauditlog',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum for tamper detection', max_length=64, verbose_name='Integrity Checksum'),
        ),
        migrations.AddField(
            model_name='publicauditlog',
            name='new_values',
            field=models.JSONField(blank=True, default=dict, help_text='New values after change', verbose_name='New Values'),
        ),
        migrations.AddField(
            model_name='publicauditlog',
            name='old_values',
            field=models.JSONField(blank=True, default=dict, help_text='Previous values before change', verbose_name='Old Values'),
        ),
        migrations.AddField(
            model_name='publicauditlog',
            name='tenant_schema',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tenant Schema'),
        ),
        migrations.AddField(
            model_name='publicauditlog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='publicauditlog',
            name='user_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Username'),
        ),
    ]
