# Generated by Django 4.2.7 on 2025-09-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tenant_id',
        ),
    ]
