# Generated by Django 4.2.7 on 2025-09-18 22:18

from django.db import migrations, models
import zargar.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_tenant_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', zargar.core.models.TenantAwareUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_schema',
            field=models.CharField(blank=True, help_text='Associated tenant schema name for data isolation', max_length=100, null=True, verbose_name='Tenant Schema'),
        ),
    ]
