# Generated by Django 4.2.7 on 2025-09-18 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers_user_tenant_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tenant_schema',
        ),
    ]
