# Generated by Django 4.2.24 on 2025-09-19 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_groups_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('tenant_created', 'Tenant Created'), ('tenant_suspended', 'Tenant Suspended'), ('impersonation_start', 'Impersonation Started'), ('impersonation_end', 'Impersonation Ended'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('2fa_verified', '2FA Verified'), ('2fa_failed', '2FA Failed'), ('backup_token_used', 'Backup Token Used')], max_length=50, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('secret_key', models.CharField(help_text='Base32 encoded secret key for TOTP generation', max_length=32, verbose_name='Secret Key')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether the device has been confirmed by successful verification', verbose_name='Is Confirmed')),
                ('backup_tokens', models.JSONField(blank=True, default=list, help_text='List of one-time backup tokens for emergency access', verbose_name='Backup Tokens')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp when the device was last used for verification', null=True, verbose_name='Last Used At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'TOTP Device',
                'verbose_name_plural': 'TOTP Devices',
                'db_table': 'core_totp_device',
            },
        ),
    ]
