# Generated by Django 4.2.24 on 2025-09-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_security_models_fix'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__user_id_da8961_idx',
            old_name='core_audit__user_id_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__content_f4dad2_idx',
            old_name='core_audit__content_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__action_5c03c3_idx',
            old_name='core_audit__action_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__ip_addr_834852_idx',
            old_name='core_audit__ip_addr_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__tenant__619cdc_idx',
            old_name='core_audit__tenant__b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitattempt',
            new_name='core_rate_l_identif_1492d0_idx',
            old_name='core_rate_l_identif_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitattempt',
            new_name='core_rate_l_window__e773ff_idx',
            old_name='core_rate_l_window__b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitattempt',
            new_name='core_rate_l_is_bloc_b230d6_idx',
            old_name='core_rate_l_is_bloc_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='core_securi_event_t_5d07cd_idx',
            old_name='core_securi_event_t_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='core_securi_ip_addr_d14813_idx',
            old_name='core_securi_ip_addr_e8b7c5_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='core_securi_user_id_f0100c_idx',
            old_name='core_securi_user_id_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='core_securi_severit_43e241_idx',
            old_name='core_securi_severit_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='suspiciousactivity',
            new_name='core_suspic_activit_359c1b_idx',
            old_name='core_suspic_activit_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='suspiciousactivity',
            new_name='core_suspic_user_id_b8ebae_idx',
            old_name='core_suspic_user_id_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='suspiciousactivity',
            new_name='core_suspic_ip_addr_27b49b_idx',
            old_name='core_suspic_ip_addr_b8e7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='suspiciousactivity',
            new_name='core_suspic_is_inve_5b020e_idx',
            old_name='core_suspic_is_inve_b8e7b8_idx',
        ),
    ]
