# Generated by Django 4.2.24 on 2025-09-21 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='نام قالب (Template Name)')),
                ('name_persian', models.CharField(max_length=200, verbose_name='نام فارسی (Persian Name)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات (Description)')),
                ('report_type', models.CharField(choices=[('trial_balance', 'ترازنامه آزمایشی (Trial Balance)'), ('profit_loss', 'صورت سود و زیان (Profit & Loss)'), ('balance_sheet', 'ترازنامه (Balance Sheet)'), ('inventory_valuation', 'گزارش ارزش\u200cگذاری موجودی (Inventory Valuation)'), ('customer_aging', 'گزارش سن مطالبات مشتریان (Customer Aging)'), ('sales_summary', 'خلاصه فروش (Sales Summary)'), ('gold_price_analysis', 'تحلیل قیمت طلا (Gold Price Analysis)'), ('installment_summary', 'خلاصه اقساط (Installment Summary)'), ('custom', 'گزارش سفارشی (Custom Report)')], max_length=30, verbose_name='نوع گزارش (Report Type)')),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='فرمت پیش\u200cفرض (Default Format)')),
                ('default_period', models.CharField(choices=[('daily', 'روزانه (Daily)'), ('weekly', 'هفتگی (Weekly)'), ('monthly', 'ماهانه (Monthly)'), ('quarterly', 'فصلی (Quarterly)'), ('yearly', 'سالانه (Yearly)'), ('custom', 'سفارشی (Custom)')], default='monthly', max_length=20, verbose_name='دوره پیش\u200cفرض (Default Period)')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='JSON configuration for report-specific parameters', verbose_name='پارامترهای گزارش (Report Parameters)')),
                ('include_charts', models.BooleanField(default=True, verbose_name='شامل نمودار (Include Charts)')),
                ('include_summary', models.BooleanField(default=True, verbose_name='شامل خلاصه (Include Summary)')),
                ('show_comparisons', models.BooleanField(default=False, verbose_name='نمایش مقایسه (Show Comparisons)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (Is Active)')),
                ('is_system_template', models.BooleanField(default=False, help_text='System templates cannot be deleted', verbose_name='قالب سیستمی (System Template)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'قالب گزارش (Report Template)',
                'verbose_name_plural': 'قالب\u200cهای گزارش (Report Templates)',
                'ordering': ['name_persian', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='نام برنامه (Schedule Name)')),
                ('name_persian', models.CharField(max_length=200, verbose_name='نام فارسی (Persian Name)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات (Description)')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='فرمت خروجی (Output Format)')),
                ('frequency', models.CharField(choices=[('daily', 'روزانه (Daily)'), ('weekly', 'هفتگی (Weekly)'), ('monthly', 'ماهانه (Monthly)'), ('quarterly', 'فصلی (Quarterly)'), ('yearly', 'سالانه (Yearly)')], max_length=20, verbose_name='تناوب (Frequency)')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع (Start Date)')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for indefinite scheduling', null=True, verbose_name='تاریخ پایان (End Date)')),
                ('execution_time', models.TimeField(default='08:00:00', verbose_name='زمان اجرا (Execution Time)')),
                ('timezone_name', models.CharField(default='Asia/Tehran', max_length=50, verbose_name='منطقه زمانی (Timezone)')),
                ('delivery_method', models.CharField(choices=[('email', 'ایمیل (Email)'), ('sms', 'پیامک (SMS)'), ('dashboard', 'داشبورد (Dashboard Only)'), ('file_storage', 'ذخیره فایل (File Storage)')], default='dashboard', max_length=20, verbose_name='روش تحویل (Delivery Method)')),
                ('email_recipients', models.JSONField(blank=True, default=list, help_text='List of email addresses', verbose_name='گیرندگان ایمیل (Email Recipients)')),
                ('sms_recipients', models.JSONField(blank=True, default=list, help_text='List of phone numbers', verbose_name='گیرندگان پیامک (SMS Recipients)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (Is Active)')),
                ('last_execution', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اجرا (Last Execution)')),
                ('next_execution', models.DateTimeField(blank=True, null=True, verbose_name='اجرای بعدی (Next Execution)')),
                ('execution_count', models.PositiveIntegerField(default=0, verbose_name='تعداد اجرا (Execution Count)')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='تعداد موفق (Success Count)')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ناموفق (Failure Count)')),
                ('custom_parameters', models.JSONField(blank=True, default=dict, verbose_name='پارامترهای سفارشی (Custom Parameters)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate', verbose_name='قالب گزارش (Report Template)')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'برنامه گزارش (Report Schedule)',
                'verbose_name_plural': 'برنامه\u200cهای گزارش (Report Schedules)',
                'ordering': ['name_persian', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('generation_id', models.CharField(max_length=50, unique=True, verbose_name='شناسه تولید (Generation ID)')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع (Start Date)')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان (End Date)')),
                ('start_date_shamsi', models.CharField(blank=True, max_length=10, verbose_name='تاریخ شروع شمسی (Shamsi Start Date)')),
                ('end_date_shamsi', models.CharField(blank=True, max_length=10, verbose_name='تاریخ پایان شمسی (Shamsi End Date)')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='فرمت خروجی (Output Format)')),
                ('custom_parameters', models.JSONField(blank=True, default=dict, verbose_name='پارامترهای سفارشی (Custom Parameters)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار (Pending)'), ('processing', 'در حال پردازش (Processing)'), ('completed', 'تکمیل شده (Completed)'), ('failed', 'ناموفق (Failed)'), ('cancelled', 'لغو شده (Cancelled)')], default='pending', max_length=20, verbose_name='وضعیت (Status)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع (Started At)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل (Completed At)')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='مسیر فایل (File Path)')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='اندازه فایل (File Size in bytes)')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود (Download Count)')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا (Error Message)')),
                ('generation_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='زمان تولید (Generation Time in seconds)')),
                ('record_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد رکورد (Record Count)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='reports.reporttemplate', verbose_name='قالب گزارش (Report Template)')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'تولید گزارش (Report Generation)',
                'verbose_name_plural': 'تولیدات گزارش (Report Generations)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('cache_key', models.CharField(max_length=255, unique=True, verbose_name='کلید کش (Cache Key)')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع (Start Date)')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان (End Date)')),
                ('parameters_hash', models.CharField(max_length=64, verbose_name='هش پارامترها (Parameters Hash)')),
                ('cached_data', models.JSONField(verbose_name='داده\u200cهای کش شده (Cached Data)')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='مسیر فایل (File Path)')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده (Hit Count)')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='آخرین دسترسی (Last Accessed)')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا (Expires At)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_reports', to='reports.reporttemplate', verbose_name='قالب گزارش (Report Template)')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'کش گزارش (Report Cache)',
                'verbose_name_plural': 'کش گزارش\u200cها (Report Caches)',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['report_type'], name='reports_rep_report__f68e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_active'], name='reports_rep_is_acti_4b0ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_system_template'], name='reports_rep_is_syst_b979d6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['is_active'], name='reports_rep_is_acti_7832b3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['next_execution'], name='reports_rep_next_ex_19774c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['frequency'], name='reports_rep_frequen_1e97ea_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['template'], name='reports_rep_templat_684edd_idx'),
        ),
        migrations.AddIndex(
            model_name='reportgeneration',
            index=models.Index(fields=['generation_id'], name='reports_rep_generat_be34b7_idx'),
        ),
        migrations.AddIndex(
            model_name='reportgeneration',
            index=models.Index(fields=['status'], name='reports_rep_status_cc900b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportgeneration',
            index=models.Index(fields=['template'], name='reports_rep_templat_c0a3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportgeneration',
            index=models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_a71624_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcache',
            index=models.Index(fields=['cache_key'], name='reports_rep_cache_k_6abaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcache',
            index=models.Index(fields=['template'], name='reports_rep_templat_f80394_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcache',
            index=models.Index(fields=['expires_at'], name='reports_rep_expires_9e7899_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcache',
            index=models.Index(fields=['last_accessed'], name='reports_rep_last_ac_f3c478_idx'),
        ),
    ]
