# Generated by Django 4.2.24 on 2025-09-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportgeneration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportgeneration',
            name='template',
        ),
        migrations.RemoveField(
            model_name='reportgeneration',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='template',
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ReportCache',
        ),
        migrations.DeleteModel(
            name='ReportGeneration',
        ),
        migrations.DeleteModel(
            name='ReportSchedule',
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
    ]
