# Generated by Django 4.2.24 on 2025-09-20 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for this impersonation session', unique=True, verbose_name='Session ID')),
                ('admin_user_id', models.IntegerField(help_text='ID of the super admin performing impersonation', verbose_name='Admin User ID')),
                ('admin_username', models.CharField(help_text='Username of the super admin performing impersonation', max_length=150, verbose_name='Admin Username')),
                ('target_user_id', models.IntegerField(help_text='ID of the user being impersonated', verbose_name='Target User ID')),
                ('target_username', models.CharField(help_text='Username of the user being impersonated', max_length=150, verbose_name='Target Username')),
                ('tenant_schema', models.CharField(help_text='Schema name of the tenant where impersonation occurred', max_length=100, verbose_name='Tenant Schema')),
                ('tenant_domain', models.CharField(help_text='Domain of the tenant where impersonation occurred', max_length=253, verbose_name='Tenant Domain')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='When the impersonation session started', verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the impersonation session ended', null=True, verbose_name='End Time')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which impersonation was initiated', verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', verbose_name='User Agent')),
                ('reason', models.TextField(blank=True, help_text='Reason for impersonation (optional)', verbose_name='Reason')),
                ('actions_performed', models.JSONField(blank=True, default=list, help_text='List of actions performed during impersonation', verbose_name='Actions Performed')),
                ('pages_visited', models.JSONField(blank=True, default=list, help_text='List of pages visited during impersonation', verbose_name='Pages Visited')),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flag indicating if this session was flagged as suspicious', verbose_name='Is Suspicious')),
                ('security_notes', models.TextField(blank=True, help_text='Additional security notes about this session', verbose_name='Security Notes')),
            ],
            options={
                'verbose_name': 'Impersonation Session',
                'verbose_name_plural': 'Impersonation Sessions',
                'db_table': 'admin_impersonation_session',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['admin_user_id', 'start_time'], name='admin_imper_admin_u_6ae6b4_idx'), models.Index(fields=['target_user_id', 'start_time'], name='admin_imper_target__ed8738_idx'), models.Index(fields=['tenant_schema', 'start_time'], name='admin_imper_tenant__e3a00e_idx'), models.Index(fields=['status', 'start_time'], name='admin_imper_status_307a89_idx'), models.Index(fields=['session_id'], name='admin_imper_session_194767_idx')],
            },
        ),
    ]
