# Generated by Django 4.2.24 on 2025-09-20 22:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_backupjob_backupschedule_restorejob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorejob',
            name='restore_type',
            field=models.CharField(choices=[('full_system', 'Full System Restore'), ('single_tenant', 'Single Tenant Restore'), ('configuration', 'Configuration Restore'), ('snapshot_restore', 'Snapshot Restore')], max_length=20, verbose_name='Restore Type'),
        ),
        migrations.CreateModel(
            name='TenantSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Snapshot ID')),
                ('name', models.CharField(max_length=200, verbose_name='Snapshot Name')),
                ('snapshot_type', models.CharField(choices=[('pre_operation', 'Pre-Operation Snapshot'), ('manual', 'Manual Snapshot'), ('scheduled', 'Scheduled Snapshot')], default='pre_operation', max_length=20, verbose_name='Snapshot Type')),
                ('tenant_schema', models.CharField(help_text='Schema name of the tenant being snapshotted', max_length=100, verbose_name='Tenant Schema')),
                ('tenant_domain', models.CharField(blank=True, help_text='Domain of the tenant being snapshotted', max_length=253, verbose_name='Tenant Domain')),
                ('operation_description', models.TextField(help_text='Description of the high-risk operation requiring snapshot', verbose_name='Operation Description')),
                ('operation_metadata', models.JSONField(default=dict, help_text='Additional metadata about the operation', verbose_name='Operation Metadata')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('expires_at', models.DateTimeField(help_text='When this snapshot will be automatically deleted', verbose_name='Expires At')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Snapshot File Path')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='File Size (Bytes)')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Progress Percentage')),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='Created By ID')),
                ('created_by_username', models.CharField(blank=True, max_length=150, verbose_name='Created By Username')),
                ('restored_at', models.DateTimeField(blank=True, help_text='When this snapshot was used for restoration', null=True, verbose_name='Restored At')),
                ('restored_by_id', models.IntegerField(blank=True, null=True, verbose_name='Restored By ID')),
                ('restored_by_username', models.CharField(blank=True, max_length=150, verbose_name='Restored By Username')),
                ('backup_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.backupjob', verbose_name='Associated Backup Job')),
            ],
            options={
                'verbose_name': 'Tenant Snapshot',
                'verbose_name_plural': 'Tenant Snapshots',
                'db_table': 'admin_tenant_snapshot',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_schema', 'created_at'], name='admin_tenan_tenant__3a5c47_idx'), models.Index(fields=['status', 'expires_at'], name='admin_tenan_status_0b9d0d_idx'), models.Index(fields=['snapshot_type', 'created_at'], name='admin_tenan_snapsho_54a6f4_idx'), models.Index(fields=['snapshot_id'], name='admin_tenan_snapsho_d5b686_idx')],
            },
        ),
    ]
