# Generated by Django 4.2.24 on 2025-09-21 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_restorejob_restore_type_tenantsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Alert ID')),
                ('title', models.CharField(max_length=200, verbose_name='Alert Title')),
                ('description', models.TextField(verbose_name='Alert Description')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20, verbose_name='Severity Level')),
                ('category', models.CharField(help_text='Category like database, redis, celery, etc.', max_length=50, verbose_name='Alert Category')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('threshold_value', models.FloatField(blank=True, help_text='Threshold value that was exceeded', null=True, verbose_name='Threshold Value')),
                ('current_value', models.FloatField(blank=True, help_text='Current value when alert was triggered', null=True, verbose_name='Current Value')),
                ('notifications_sent', models.JSONField(default=list, help_text='List of notifications sent for this alert', verbose_name='Notifications Sent')),
                ('acknowledged_by_id', models.IntegerField(blank=True, null=True, verbose_name='Acknowledged By ID')),
                ('acknowledged_by_username', models.CharField(blank=True, max_length=150, verbose_name='Acknowledged By Username')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
            ],
            options={
                'verbose_name': 'System Health Alert',
                'verbose_name_plural': 'System Health Alerts',
                'db_table': 'admin_system_health_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('cpu_usage', 'CPU Usage'), ('memory_usage', 'Memory Usage'), ('disk_usage', 'Disk Usage'), ('database_connections', 'Database Connections'), ('redis_memory', 'Redis Memory Usage'), ('celery_workers', 'Celery Workers'), ('response_time', 'Response Time'), ('error_rate', 'Error Rate')], max_length=30, verbose_name='Metric Type')),
                ('value', models.FloatField(help_text='Numeric value of the metric', verbose_name='Metric Value')),
                ('unit', models.CharField(help_text='Unit of measurement (%, MB, ms, etc.)', max_length=20, verbose_name='Unit')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('hostname', models.CharField(blank=True, help_text='Server hostname where metric was collected', max_length=100, verbose_name='Hostname')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
            ],
            options={
                'verbose_name': 'System Health Metric',
                'verbose_name_plural': 'System Health Metrics',
                'db_table': 'admin_system_health_metric',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='tenantsnapshot',
            name='admin_tenan_tenant__3a5c47_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantsnapshot',
            name='admin_tenan_status_0b9d0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantsnapshot',
            name='admin_tenan_snapsho_54a6f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantsnapshot',
            name='admin_tenan_snapsho_d5b686_idx',
        ),
        migrations.RemoveField(
            model_name='tenantsnapshot',
            name='backup_job',
        ),
        migrations.RemoveField(
            model_name='tenantsnapshot',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='tenantsnapshot',
            name='operation_description',
        ),
        migrations.RemoveField(
            model_name='tenantsnapshot',
            name='operation_metadata',
        ),
        migrations.RemoveField(
            model_name='tenantsnapshot',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='tenantsnapshot',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='tenantsnapshot',
            name='restored_by_id',
        ),
        migrations.RemoveField(
            model_name='tenantsnapshot',
            name='restored_by_username',
        ),
        migrations.RemoveField(
            model_name='tenantsnapshot',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='tenantsnapshot',
            name='tenant_domain',
        ),
        migrations.AddField(
            model_name='tenantsnapshot',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='Snapshot Metadata'),
        ),
        migrations.AlterField(
            model_name='tenantsnapshot',
            name='expires_at',
            field=models.DateTimeField(help_text='When this snapshot expires and can be deleted', verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='tenantsnapshot',
            name='snapshot_type',
            field=models.CharField(choices=[('pre_operation', 'Pre-Operation Snapshot'), ('manual', 'Manual Snapshot'), ('scheduled', 'Scheduled Snapshot')], max_length=20, verbose_name='Snapshot Type'),
        ),
        migrations.AddIndex(
            model_name='systemhealthmetric',
            index=models.Index(fields=['metric_type', 'timestamp'], name='admin_syste_metric__27aa60_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthmetric',
            index=models.Index(fields=['timestamp'], name='admin_syste_timesta_b8e39b_idx'),
        ),
        migrations.AddField(
            model_name='systemhealthalert',
            name='source_metric',
            field=models.ForeignKey(blank=True, help_text='Metric that triggered this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.systemhealthmetric', verbose_name='Source Metric'),
        ),
        migrations.AddIndex(
            model_name='systemhealthalert',
            index=models.Index(fields=['status', 'severity', 'created_at'], name='admin_syste_status_de3753_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthalert',
            index=models.Index(fields=['category', 'status'], name='admin_syste_categor_690516_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthalert',
            index=models.Index(fields=['alert_id'], name='admin_syste_alert_i_5c9e56_idx'),
        ),
    ]
