# Generated by Django 4.2.24 on 2025-09-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_add_settings_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this security policy', max_length=200, verbose_name='Policy Name')),
                ('policy_type', models.CharField(choices=[('password', 'Password Policy'), ('session', 'Session Policy'), ('rate_limit', 'Rate Limiting Policy'), ('authentication', 'Authentication Policy'), ('access_control', 'Access Control Policy')], max_length=50, verbose_name='Policy Type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is currently active', verbose_name='Is Active')),
                ('configuration', models.JSONField(default=dict, help_text='JSON configuration for the security policy', verbose_name='Policy Configuration')),
                ('description', models.TextField(blank=True, help_text='Description of what this policy does', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.IntegerField(blank=True, help_text='ID of the user who created this policy', null=True, verbose_name='Created By ID')),
                ('created_by_username', models.CharField(blank=True, help_text='Username of the user who created this policy', max_length=150, verbose_name='Created By Username')),
                ('updated_by_id', models.IntegerField(blank=True, help_text='ID of the user who last updated this policy', null=True, verbose_name='Updated By ID')),
                ('updated_by_username', models.CharField(blank=True, help_text='Username of the user who last updated this policy', max_length=150, verbose_name='Updated By Username')),
            ],
            options={
                'verbose_name': 'Security Policy',
                'verbose_name_plural': 'Security Policies',
                'db_table': 'admin_security_policy',
                'ordering': ['policy_type', 'name'],
                'indexes': [models.Index(fields=['policy_type', 'is_active'], name='admin_secur_policy__44a77d_idx'), models.Index(fields=['is_active', 'updated_at'], name='admin_secur_is_acti_4aa2a1_idx')],
                'unique_together': {('policy_type', 'name')},
            },
        ),
    ]
